service: shipcore-api
frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  profile: algocart
  environment:
    MONGO_URI_PARAM: /shipcore/mongo_uri
  iam:
    role:
      statements:
        - Effect: Allow
          Action: ssm:GetParameter
          Resource: arn:aws:ssm:us-east-1:*:parameter/shipcore/*
  httpApi:
    cors: true

functions:
  get_product:
    handler: get_product.lambda_handler
    layers:
      - arn:aws:lambda:us-east-1:467866448248:layer:common:2
    events:
      - httpApi:
          path: /products
          method: GET

  add_product:
    handler: add_product.lambda_handler
    layers:
      - arn:aws:lambda:us-east-1:467866448248:layer:common:2
    events:
      - httpApi:
          path: /products
          method: POST
