service: shipcore-api
frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  profile: algocart
  layers:
    - arn:aws:lambda:us-east-1:467866448248:layer:common:5
  iam:
    role:
      statements:
        - Effect: Allow
          Action: ssm:GetParameter
          Resource: arn:aws:ssm:us-east-1:*:parameter/shipcore/*
  httpApi:
    cors: true

functions:
  get_product:
    handler: get_product.lambda_handler
    events:
      - httpApi:
          path: /products
          method: GET

  add_product:
    handler: add_product.lambda_handler
    events:
      - httpApi:
          path: /products
          method: POST

  ebayAuth:
    handler: ebay_auth.lambda_handler
    events:
      - httpApi:
          path: /ebay/auth
          method: POST

  ebayStatus:
    handler: ebay_status.lambda_handler
    events:
      - httpApi:
          path: /ebay/status
          method: GET